<b><h1>Basic python</h1></b>

<h3>1. Split this string</h3>

In [1]:
s = "Hi there Sam!"

In [2]:
s = "Hi there Sam!"
x=s.split()
print(x)

['Hi', 'there', 'Sam!']


<h3>2. Use .format() to print the following string.</h3>

<h4>Output should be: The diameter of Earth is 12742 kilometers.</h4>

In [3]:
planet = "Earth"
diameter = 12742
str=("The diameter of {planet} is {diameter} kilometers.")
print((str.format(planet="Earth",diameter=12742)))

The diameter of Earth is 12742 kilometers.


<h3>3. In this nest dictionary grab the word "hello"</h3>

In [4]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [5]:
d.get('target',{}).get('hello')

<h2>Numpy</h2>

In [6]:
import numpy as np

<h3>4.1 Create an array of 10 zeros?</h3>

In [7]:
arr=np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


<h3>4.2 Create an array of 10 fives?</h3>

In [8]:
arr=np.ones(10)*5
print(arr)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


<h3>5. Create an array of all the even integers from 20 to 35</h3>

In [9]:
arr=np.arange(20,36,2)
print(arr)

[20 22 24 26 28 30 32 34]


<h3>6. Create a 3x3 matrix with values ranging from 0 to 8</h3>

In [10]:
arr=np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


<h3>7. Concatenate a and b</h3>

<h4>a = np.array([1, 2, 3]), b = np.array([4, 5, 6])</h4>

In [11]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.concatenate((a,b),axis=None)

array([1, 2, 3, 4, 5, 6])

<h2>Pandas</h2>

In [12]:
import pandas as pd

<h3>8. Create a dataframe with 3 rows and 2 columns</h3>

In [13]:
d={'Name':['aaa','bbb','ccc'],
   'age':[23,30,18]}
d= pd.DataFrame((d))
print(d)

  Name  age
0  aaa   23
1  bbb   30
2  ccc   18


<h3>9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023</h3>

In [14]:
pd.date_range(start='1/1/2023', end='10/02/2023')

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')

<h3>10. Create 2D list to DataFrame</h3>

<h4>lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]</h4>

In [15]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
lst = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]    
df = pd.DataFrame(lst,columns =['Tag','day','number']) 
print(df)

   Tag  day  number
0    1  aaa      22
1    2  bbb      25
2    3  ccc      24
